version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "fix(deps)"
      prefix-development: "chore(deps):"
    assignees:
      - "yubarajshrestha"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(actions)"
    assignees:
      - "yubarajshrestha"
